### ISSUE TITLE
Robot gives colinear error when running dripfeed programs

### ISSUE THREAD

**Issue by BrinkCompositeEngineering** [inholland-compolab/FanucAutomatedManufacturing#10]
The robot stops after the first program with a colinear error on the teachpendant. This is caused by a circular motion on the final line of program N and the first line of program N+1 contains the remainder of the circular move.

**Comment by MarcoWithag** [comment]
To prevent this issue we have to make sure that the program only contains linear movements, this is done by going to Options in RoboDK.

Options -> Program -> Minimum arc size (mm) = 1.000
                                 -> Maximum arc size (mm) = 1.000

Now only linear movements will be generated
